name: example
description: How to use Aspectd
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  aspectd_annotation:
    path: ../aspectd_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
