name: aspectd_transformer
description: handle with aop annotation
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  kernel: any

dependency_overrides:
  kernel:
    git:
      url: git@github.com:alibaba-flutter/sdk.git
      ref: stable/v1.22.6
      path: pkg/kernel
